### PR TITLE
Introducing i18n to the project

### PR DESCRIPTION
**Pull request by andrewmiroshnichenko**
Network details page + navbar
image

Networks
image

Calendar
image

Login page
image

Charts
image

### CODE REVIEW

**Comment by segrey11** [comment]
Wouldn't it better to create one global object with translations instead of per-component division?

**Comment by andrewmiroshnichenko** [comment]
> Wouldn't it better to create one global object with translations instead of per-component division?

Why this can be beneficial?

**Comment by segrey11** [comment]
All translations are in one place. No need to import locales in each componen. Possibility to re-use the same translations in different components.

**Comment by andrewmiroshnichenko** [comment]
> All translations are in one place.
This really can be a nice idea. But in a case if someone want to find text in a really long file, he'll need to use Ctrl+F anyway, which isn't so different from search across whole codebase for this phrase.
But yeah, this argument is valid.

> No need to import locales in each component
But in this case you'll need to import translation from that big file. Or from store, containing that file. Anyway, translations need to be imported in components.

> Possibility to re-use the same translations in different components.
This is really opinionated idea. In some rare cases we can re-use translations, if components that are using them are logically bounded and it's likely that translations will be changed (if change will be needed) in all of the components.
But usually that creates a big mess, when developers start to re-use translations for completely separated components. ANd in case of translation change for one of them, there a headache arise, to came up with new proper keys for every separated component. This is a bad practice.

**Pull request merged**
